Feature/citizen dashboard view
ICS-233-SIMPLE/simple-java pull request #30
Opened 2021-11-05 19:59 UTC by mehsheed

![852852](https://user-images.githubusercontent.com/19487622/140570890-41d4d8b4-1e68-44c0-99ee-4758123a1426.jpg)

2021-11-05 20:41 UTC, Vishwas-Adiga requested changes

2021-11-05 20:41 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/controllers/RouteController.java
> +
Fix whitespace please

2021-11-05 20:41 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/impl/views/CitizenDashboardViewImpl.java
> + */
Remove comment?

2021-11-05 20:41 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/impl/views/CitizenDashboardViewImpl.java
> + */
Please add a doc line

2021-11-05 20:41 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/impl/views/CitizenDashboardViewImpl.java
> +
Whitespace.
Do Ctrl+Shift+F on all committed files

2021-11-05 20:41 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/impl/views/CitizenDashboardViewImpl.java
> +	 */
Remove or add javadoc?

2021-11-05 20:41 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/views/CitizenDashboardView.java
> +	JButton getAppForNewPPButton();
Please use full name, i.e., getApplicationForNewPassportButton

2021-11-05 20:41 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/views/CitizenDashboardView.java
> +	JButton getredirect2AppstepsButton();
Pascal casing, and please use full name (Two instead of 2)

2021-11-05 20:45 UTC, Rea-Mammen commented
Could you please add an icon for the frame? 
https://github.com/ICS-233-SIMPLE/simple-java/blob/2c04c4fb1115efbccd1b06ceb58d3f8b74b50484/SIMPLE/src/edu/manipal/icas/simple/impl/views/CitizenLoginViewImpl.java#L158
Use this as ref

2021-11-06 01:11 UTC, Yodhin05 approved these changes

2021-11-06 08:26 UTC, Vishwas-Adiga commented on SIMPLE/.classpath
> +	<classpathentry kind="lib" path="C:/Users/sameh/Documents/GitHub/Route/simple-java/SIMPLE/lib/miglayout-4.0.jar"/>
I think you used "add external jar" in Eclipse. This classpathentry won't work on our machines. Can you change it to the ones listed in other lines?

2021-11-06 08:32 UTC, Vishwas-Adiga approved these changes
Looks good!

2021-11-06 08:40 UTC, Rea-Mammen approved these changes

2021-11-06 09:22 UTC, merged