Police Officer Dashboard View Implementation
ICS-233-SIMPLE/simple-java pull request #31
Opened 2021-11-06 19:14 UTC by mehsheed

<img width="1280" alt="wewer" src="https://user-images.githubusercontent.com/19487622/140621197-3d6284f6-f944-426a-b1e1-8a640057a5c4.png">

2021-11-06 19:25 UTC, Yodhin05 approved these changes

2021-11-06 19:30 UTC, Vishwas-Adiga requested changes

2021-11-06 19:30 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/views/PoliceDashboardView.java
> +	 */
Is a method missing here?

2021-11-06 19:30 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/views/PoliceDashboardView.java
> +    JLabel getofficerIDLabel();
Use Id instead of ID everywhere

2021-11-06 19:30 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/views/PoliceDashboardView.java
> +
Fix formatting

2021-11-06 19:30 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/impl/views/PoliceDashboardViewImpl.java
> +		// TODO Auto-generated method stub
Remove TODO comments everywhere

2021-11-06 19:30 UTC, Vishwas-Adiga commented on SIMPLE/src/edu/manipal/icas/simple/impl/views/PoliceDashboardViewImpl.java
> +	public JComboBox<String> getApplicationIdCombo() {
Please change to `...ComboBox`

2021-11-06 20:04 UTC, Vishwas-Adiga approved these changes
LGTM

2021-11-07 03:25 UTC, Rea-Mammen approved these changes

2021-11-07 03:27 UTC, merged